In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [3]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

# Read the CSV and Perform Basic Data Cleaning

In [4]:
# https://help.lendingclub.com/hc/en-us/articles/215488038-What-do-the-different-Note-statuses-mean-

columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [5]:
# Load the data
file_path = Path('../Resources/LoanStats_2019Q1.csv.zip')
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

In [6]:
#Clean up chronological records
df_string=df.select_dtypes(exclude=['float64'])
unique_values=dict(zip([i for i in df_string.columns if i not in ['loan_status']] , 
                       [df_string[i].unique().tolist() for i in df_string.columns if i not in ['loan_status']]))
unique_values

{'home_ownership': ['RENT', 'MORTGAGE', 'OWN', 'ANY'],
 'verification_status': ['Source Verified', 'Verified', 'Not Verified'],
 'issue_d': ['Mar-2019', 'Feb-2019', 'Jan-2019'],
 'pymnt_plan': ['n'],
 'initial_list_status': ['w', 'f'],
 'next_pymnt_d': ['May-2019', 'Apr-2019'],
 'application_type': ['Individual', 'Joint App'],
 'hardship_flag': ['N'],
 'debt_settlement_flag': ['N']}

In [7]:
df_encoded=pd.get_dummies(df, columns=unique_values.keys())
df_encoded

,loan_amnt,int_rate,installment,annual_inc,loan_status,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,...,issue_d_Mar-2019,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
0,10500.0,0.1719,375.35,66000.0,low_risk,27.24,0.0,0.0,8.0,0.0,...,1,1,0,1,0,1,1,0,1,1
1,25000.0,0.2000,929.09,105000.0,low_risk,20.23,0.0,0.0,17.0,1.0,...,1,1,0,1,0,1,1,0,1,1
2,20000.0,0.2000,529.88,56000.0,low_risk,24.26,0.0,0.0,8.0,0.0,...,1,1,0,1,0,1,1,0,1,1
3,10000.0,0.1640,353.55,92000.0,low_risk,31.44,0.0,1.0,10.0,1.0,...,1,1,0,1,0,1,1,0,1,1
4,22000.0,0.1474,520.39,52000.0,low_risk,18.76,0.0,1.0,14.0,0.0,...,1,1,0,1,0,1,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68812,10000.0,0.1502,346.76,26000.0,low_risk,9.60,0.0,0.0,9.0,0.0,...,0,1,0,1,0,1,1,0,1,1
68813,12000.0,0.2727,368.37,63000.0,low_risk,29.07,0.0,0.0,8.0,0.0,...,0,1,0,1,0,1,1,0,1,1
68814,5000.0,0.1992,185.62,52000.0,low_risk,14.86,0.0,0.0,5.0,1.0,...,0,1,0,1,0,1,1,0,1,1
68815,40000.0,0.0646,1225.24,520000.0,low_risk,9.96,0.0,1.0,21.0,0.0,...,0,1,1,0,0,1,1,0,1,1
68816,16000.0,0.1131,350.36,72000.0,low_risk,7.02,2.0,0.0,12.0,1.0,...,0,1,0,1,0,1,1,0,1,1

# Split the Data into Training and Testing

In [8]:
# Create our target
y = df_encoded['loan_status']
# Create our features
X = df_encoded.drop(columns=['loan_status'])

In [9]:
X.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,issue_d_Mar-2019,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.0,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.0,68817.0
mean,16677.594562,0.127718,480.652863,8.821371e+04,21.778153,0.217766,0.497697,12.587340,0.126030,17604.142828,...,0.177238,1.0,0.123879,0.876121,0.383161,0.616839,0.860340,0.139660,1.0,1.0
std,10277.348590,0.048130,288.062432,1.155800e+05,20.199244,0.718367,0.758122,6.022869,0.336797,21835.880400,...,0.381873,0.0,0.329446,0.329446,0.486161,0.486161,0.346637,0.346637,0.0,0.0
min,1000.000000,0.060000,30.890000,4.000000e+01,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.0
25%,9000.000000,0.088100,265.730000,5.000000e+04,13.890000,0.000000,0.000000,8.000000,0.000000,6293.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.0,1.0
50%,15000.000000,0.118000,404.560000,7.300000e+04,19.760000,0.000000,0.000000,11.000000,0.000000,12068.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.0,1.0
75%,24000.000000,0.155700,648.100000,1.040000e+05,26.660000,0.000000,1.000000,16.000000,0.000000,21735.000000,...,0.000000,1.0,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.0,1.0
max,40000.000000,0.308400,1676.230000,8.797500e+06,999.000000,18.000000,5.000000,72.000000,4.000000,587191.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0

In [11]:
# Check the balance of our target values
y.value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [12]:
# Split the X and y into X_train, X_test, y_train, y_test
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test= train_test_split(X, 
                                                   y, 
                                                   random_state=1)
X_train.shape

(51612, 95)

In [13]:
Counter(y_train)

Counter({'low_risk': 51366, 'high_risk': 246})

# Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble AdaBoost classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Print the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier onely, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [14]:
# Resample the training data with the RandomOversampler
from imblearn.over_sampling import RandomOverSampler

ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
Counter(y_resampled)

Counter({'low_risk': 51366, 'high_risk': 51366})

In [16]:
from imblearn.ensemble import BalancedRandomForestClassifier
brf = BalancedRandomForestClassifier( random_state=1)
brf.fit(X_train, y_train)

BalancedRandomForestClassifier(bootstrap=True, class_weight=None,
                               criterion='gini', max_depth=None,
                               max_features='auto', max_leaf_nodes=None,
                               min_impurity_decrease=0.0, min_samples_leaf=2,
                               min_samples_split=2,
                               min_weight_fraction_leaf=0.0, n_estimators=100,
                               n_jobs=1, oob_score=False, random_state=1,
                               replacement=False, sampling_strategy='auto',
                               verbose=0, warm_start=False)

In [17]:
# Calculated the balanced accuracy score
y_pred=brf.predict(X_test)
balanced_accuracy_score(y_test,y_pred)

0.7855052723466922

In [18]:
# Display the confusion matrix
confusion_matrix(y_test,y_pred)

array([[   68,    33],
       [ 1749, 15355]], dtype=int64)

In [19]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test,y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.04      0.67      0.90      0.07      0.78      0.59       101
   low_risk       1.00      0.90      0.67      0.95      0.78      0.62     17104

avg / total       0.99      0.90      0.67      0.94      0.78      0.62     17205

array([0.00995374, 0.03195562, 0.01707892, 0.01577554, 0.0160705 ,
       0.00327507, 0.00416516, 0.00782073, 0.00089767, 0.01599866,
       0.00897678, 0.01482801, 0.01653796, 0.05764917, 0.06410003,
       0.09175752, 0.0572968 , 0.00598147, 0.        , 0.        ,
       0.05174788, 0.00051683, 0.        , 0.        , 0.00218998,
       0.01073642, 0.00747188, 0.00553016, 0.00401646, 0.00641355,
       0.01431883, 0.01440243, 0.01315152, 0.00606626, 0.00458729,
       0.01616972, 0.01156494, 0.01240632, 0.00760805, 0.00686214,
       0.00960365, 0.01038009, 0.01263346, 0.01140916, 0.0127846 ,
       0.        , 0.        , 0.0116874 , 0.01502927, 0.00631944,
       0.00804558, 0.00687485, 0.01009753, 0.01701486, 0.0026174 ,
       0.00616047, 0.00953742, 0.00758615, 0.00887062, 0.00982172,
       0.00874511, 0.01145588, 0.00727378, 0.0077987 , 0.        ,
       0.        , 0.00057341, 0.00755451, 0.0099141 , 0.00683872,
       0.00121513, 0.        , 0.01535561, 0.01263661, 0.01464882,
       0.01310158, 0.        , 0.00227967, 0.00184048, 0.00208511,
       0.00275652, 0.00154722, 0.00173602, 0.00496182, 0.02353679,
       0.01351987, 0.        , 0.00041925, 0.00081252, 0.00790625,
       0.0046852 , 0.00122131, 0.00122633, 0.        , 0.        ])

array([0.09175752, 0.06410003, 0.05764917, 0.0572968 , 0.05174788,
       0.03195562, 0.02353679, 0.01707892, 0.01701486, 0.01653796,
       0.01616972, 0.0160705 , 0.01599866, 0.01577554, 0.01535561,
       0.01502927, 0.01482801, 0.01464882, 0.01440243, 0.01431883,
       0.01351987, 0.01315152, 0.01310158, 0.0127846 , 0.01263661,
       0.01263346, 0.01240632, 0.0116874 , 0.01156494, 0.01145588,
       0.01140916, 0.01073642, 0.01038009, 0.01009753, 0.00995374,
       0.0099141 , 0.00982172, 0.00960365, 0.00953742, 0.00897678,
       0.00887062, 0.00874511, 0.00804558, 0.00790625, 0.00782073,
       0.0077987 , 0.00760805, 0.00758615, 0.00755451, 0.00747188,
       0.00727378, 0.00687485, 0.00686214, 0.00683872, 0.00641355,
       0.00631944, 0.00616047, 0.00606626, 0.00598147, 0.00553016,
       0.00496182, 0.0046852 , 0.00458729, 0.00416516, 0.00401646,
       0.00327507, 0.00275652, 0.0026174 , 0.00227967, 0.00218998,
       0.00208511, 0.00184048, 0.00173602, 0.00154722, 0.00122633,
       0.00122131, 0.00121513, 0.00089767, 0.00081252, 0.00057341,
       0.00051683, 0.00041925, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])

In [50]:
# List the features sorted in descending order by feature importance
df_feature_importance = pd.DataFrame(brf.feature_importances_, index=X.columns, columns=['feature importance']).sort_values('feature importance', ascending=False)
print(df_feature_importance.to_string())

                                     feature importance
total_rec_prncp                                0.091758
total_pymnt_inv                                0.064100
total_pymnt                                    0.057649
total_rec_int                                  0.057297
last_pymnt_amnt                                0.051748
int_rate                                       0.031956
issue_d_Jan-2019                               0.023537
installment                                    0.017079
mths_since_recent_inq                          0.017015
out_prncp_inv                                  0.016538
max_bal_bc                                     0.016170
dti                                            0.016070
revol_bal                                      0.015999
annual_inc                                     0.015776
tot_hi_cred_lim                                0.015356
mo_sin_old_rev_tl_op                           0.015029
out_prncp                                      0.014828
total_bc_limit                                 0.014649
total_bal_il                                   0.014402
mths_since_rcnt_il                             0.014319
issue_d_Mar-2019                               0.013520
il_util                                        0.013152
total_il_high_credit_limit                     0.013102
bc_util                                        0.012785
total_bal_ex_mort                              0.012637
avg_cur_bal                                    0.012633
total_rev_hi_lim                               0.012406
mo_sin_old_il_acct                             0.011687
all_util                                       0.011565
num_rev_accts                                  0.011456
bc_open_to_buy                                 0.011409
tot_cur_bal                                    0.010736
acc_open_past_24mths                           0.010380
mths_since_recent_bc                           0.010098
loan_amnt                                      0.009954
pct_tl_nvr_dlq                                 0.009914
num_il_tl                                      0.009822
inq_last_12m                                   0.009604
num_actv_rev_tl                                0.009537
total_acc                                      0.008977
num_bc_tl                                      0.008871
num_op_rev_tl                                  0.008745
mo_sin_rcnt_tl                                 0.008046
next_pymnt_d_Apr-2019                          0.007906
open_acc                                       0.007821
num_sats                                       0.007799
inq_fi                                         0.007608
num_bc_sats                                    0.007586
num_tl_op_past_12m                             0.007555
open_acc_6m                                    0.007472
num_rev_tl_bal_gt_0                            0.007274
mort_acc                                       0.006875
total_cu_tl                                    0.006862
percent_bc_gt_75                               0.006839
open_il_24m                                    0.006414
mo_sin_rcnt_rev_tl_op                          0.006319
num_actv_bc_tl                                 0.006160
open_rv_12m                                    0.006066
total_rec_late_fee                             0.005981
open_act_il                                    0.005530
issue_d_Feb-2019                               0.004962
next_pymnt_d_May-2019                          0.004685
open_rv_24m                                    0.004587
inq_last_6mths                                 0.004165
open_il_12m                                    0.004016
delinq_2yrs                                    0.003275
verification_status_Not Verified               0.002757
num_accts_ever_120_pd                          0.002617
home_ownership_MORTGAGE                        0.002280
tot_coll_amt                                   0.002190
home_ownership_RENT                            0.002085
home_ownership_OWN                             0.001840
verification_status_Verified                   0.001736
verification_status_Source Verified            0.001547
application_type_Joint App                     0.001226
application_type_Individual                    0.001221
pub_rec_bankruptcies                           0.001215
pub_rec                                        0.000898
initial_list_status_w                          0.000813
num_tl_90g_dpd_24m                             0.000573
collections_12_mths_ex_med                     0.000517
initial_list_status_f                          0.000419
pymnt_plan_n                                   0.000000
hardship_flag_N                                0.000000
num_tl_30dpd                                   0.000000
home_ownership_ANY                             0.000000
tax_liens                                      0.000000
num_tl_120dpd_2m                               0.000000
recoveries                                     0.000000
collection_recovery_fee                        0.000000
policy_code                                    0.000000
acc_now_delinq                                 0.000000
delinq_amnt                                    0.000000
chargeoff_within_12_mths                       0.000000
debt_settlement_flag_N                         0.000000

### Easy Ensemble AdaBoost Classifier

In [52]:
# Train the Classifier
from sklearn.ensemble import AdaBoostClassifier
model=AdaBoostClassifier(n_estimators=100,random_state=1)
model.fit(X_train,y_train)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1.0,
                   n_estimators=100, random_state=1)

In [53]:
# Calculated the balanced accuracy score
y_pred=model.predict(X_test)
balanced_accuracy_score(y_test,y_pred)

0.6879726472413378

In [54]:
# Display the confusion matrix
confusion_matrix(y_test,y_pred)

array([[   38,    63],
       [    5, 17099]], dtype=int64)

In [55]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test,y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.88      0.38      1.00      0.53      0.61      0.35       101
   low_risk       1.00      1.00      0.38      1.00      0.61      0.40     17104

avg / total       1.00      1.00      0.38      1.00      0.61      0.40     17205

In [ ]:
### Easy Ensemble Classifier